name: flutter_wheater
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.16.1 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    dio: ^4.0.5
    location: ^4.2.0
    permission_handler: ^9.2.0
    flutter_modular: ^4.5.0
    flutter_native_splash: ^1.2.0
    animated_splash_screen: ^1.2.0
    intl: ^0.17.0
    flutter_svg: ^1.0.3

flutter_native_splash:
    color: "#353535"
    android: true
    ios: true

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^1.0.0
    mocktail: ^0.3.0

flutter:
    
    uses-material-design: true
    assets: 
        - assets/images/weatherApp.png
        - assets/images/chuva_intensa.svg
        - assets/images/chuva.svg
        - assets/images/sol.svg
        - assets/images/nublado.svg
    
    fonts:
        - family: DMSans
          fonts:
            - asset: fonts/dm_sans/DMSans-Medium.ttf
              weight: 500
            - asset: fonts/dm_sans/DMSans-Bold.ttf
              weight: 700
        - family: Inter
          fonts:
            - asset: fonts/inter/Inter-Medium.ttf
              weight: 500
            - asset: fonts/inter/Inter-Regular.ttf
        - family: Switzer
          fonts:
            - asset: fonts/switzer/Switzer-Light.otf
            - asset: fonts/switzer/Switzer-Medium.otf
              weight: 500